server:
  port: 8762
spring:
  application:
    name: eureka-client
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/blgmanager?useUnicode=true&characterEncoding=utf-8
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver

#mybatis.mapper-locations=classpath:mapping/*.xml
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
mybatis:
  mapper-locations: classpath:mapping/*.xml
